name: Update Values

on:
  schedule:
    - cron:  '00 10 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run script to fetch data from airtable
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: |
          ./scripts/fetch_from_airtable.sh

      - name: Commit to the repo
        run: |
          git config --global user.name "RayanRal"
          git config --global user.email "rayanral@gmail.com"
          git add .
          git commit -am "Updated data"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}